### ISSUE TITLE
Current build broken

### ISSUE THREAD

**Issue by darklight9811** [LaNsHoR/native-json-editor#2]
`package.json` refers to inexistent entry file
it needs to be transpiled into cjs/esm builds (recommend [tsup](https://github.com/egoist/tsup) for that)
JSON-Editor class extends undefined HTMLElement

**Comment by LaNsHoR** [comment]
Thanks, I'll fix it hopefully today!

**Comment by LaNsHoR** [comment]
Sorry for the long wait. Fixed the broken reference to the entry file.

It should work out of the box now, please let me know if not.
